### PR TITLE
Get from local dataset

### LINKED ISSUE #93: Manage datasets in `artiq-proxy` and return it immediately for "get" requests
### Feature you want to implement
Currently, the `artiq-proxy` server does not manage the whole datasets, so `get_master_dataset()` performs RPC to get the artiq master's datasets.
However, this implementation has a synchronization issue: some modifications could be dropped or duplicated.
To resolve this issue, I will manage datasets in `artiq-proxy` itself and return it directly for get-dataset requests.

### How the feature is implemented
`get_master_dataset()` does not perform RPC to artiq master. Instead, it returns immediately the dataset of itself.

### PR DESCRIPTION
**Pull request by kangz12345**
This closes #93.

### CODE REVIEW

**Comment by kangz12345** [comment]
I accidentally deleted the branch.

**Comment by BECATRUE** [comment]
Why did you close this temporarily? Just for debugging?

**Review by BECATRUE — APPROVED** [review]
LGTM!

**Comment by kangz12345** [comment]
> Why did you close this temporarily? Just for debugging?

I deleted the branch by mistake, and the PR was closed automatically.

**Pull request merged**
