### PR TITLE
Merge `develop` to `release` for v2.0.0

### PR DESCRIPTION
**Pull request by BECATRUE**
This is a part of #139.

### CODE REVIEW

**Review by kangz12345 — COMMENTED** [review]
Oh, did we decide to include the specific config information of our system here?

**Comment by BECATRUE** [comment]
What does the specific config information mean? @kangz12345

**Comment by kangz12345** [comment]
> What does the specific config information mean? @kangz12345

The contents of the `config.json` file!

**Comment by BECATRUE** [comment]
Umm.. As I remember, we haven't decide how to do.
I think it'd be better to write down just now for security.
Do you want to get rid of more information? @kangz12345

**Comment by kangz12345** [comment]
Since this is a repo for general use, the system specific information should not be included. Also it would be better for security.
Let's make the config template just like iquip.

**Comment by BECATRUE** [comment]
Then, please check this PR again. @kangz12345

**Review by kangz12345 — APPROVED** [review]

**Pull request merged**
