### PR TITLE
Get the code of the specified experiment

### LINKED ISSUE #18: Get the code of the specified experiment
### Feature you want to implement
We need to get the specific experiment code to visualize it in the iquip project. snu-quiqcl/iquip#50

### How the feature is implemented
Just read the experiment file and return it as a (long) string.

### PR DESCRIPTION
**Pull request by BECATRUE**
This PR will close #18.

I implemented fetching a specific file code using file I/O.

### CODE REVIEW

**Review by kangz12345 — APPROVED** [review]
LGTM

**Comment by kangz12345** [comment]
Let's wait for the new developers to open the first PR. Until then, let's merge after just a single code owner's review.
I allowed bypassing the branch protection for administrators.

**Comment by BECATRUE** [comment]
> Let's wait for the new developers to open the first PR. Until then, let's merge after just a single code owner's review. I allowed bypassing the branch protection for administrators.

Then, I can merge this now, right?

**Comment by kangz12345** [comment]
Yes you can!

**Pull request merged**
